# Use a Python image with uv pre-installed
FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim

RUN --mount=type=cache,target=/var/cache/apt/archives \
        --mount=type=cache,target=/var/lib/apt/lists \
        apt-get update && apt-get install -y git

# Install the project into `/app`
WORKDIR /app

# Enable bytecode compilation
ENV UV_COMPILE_BYTECODE=1

# Copy from the cache instead of linking since it's a mounted volume
ENV UV_LINK_MODE=copy

# Create the virtual envionment
RUN --mount=type=cache,target=/root/.cache/uv \
    uv venv -p python3.12 --seed /opt/pio

# Install platformio
RUN --mount=type=cache,target=/root/.cache/uv \
    uv pip install --python /opt/pio/bin/python platformio

ENV PATH="/opt/pio/bin:$PATH"

RUN --mount=type=cache,target=/root/.platformio/.cache /opt/pio/bin/platformio pkg install -g -t https://github.com/sparkfun/Arduino_Apollo3#v2.2.1 && rm -Rf .platformio/packages/framework-arduinoapollo3/.git
RUN --mount=type=cache,target=/root/.platformio/.cache /opt/pio/bin/platformio pkg install -g -t platformio/tool-scons
RUN --mount=type=cache,target=/root/.platformio/.cache /opt/pio/bin/platformio pkg install -g -t platformio/toolchain-gccarmnoneeabi@1.90201.191206
RUN --mount=type=cache,target=/root/.platformio/.cache /opt/pio/bin/platformio settings set enable_telemetry 0 && /opt/pio/bin/platformio settings set check_platformio_interval 0
#RUN /opt/pio/bin/platformio pkg install -g -p git+https://github.com/nigelb/platform-apollo3blue

ENTRYPOINT  ["platformio"]

# docker build . -t ghcr.io/nigelb/arduino_apollo3:2.2.1 -f Dockerfile.arduino_apollo3

LABEL description="A container for CI use on https://github.com/nigelb/platform-apollo3blue"
